spring:
  datasource:
    password: gymatedb
    username: gymate
    url: jdbc:mysql://mysql:3306/GYMate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: redis
      port: 6379
server:
  port: 8088