spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 405172535942-sc1t0tli99i1hh1po16ctoj8lcvpfmhn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://gymate.duckdns.org/login/oauth2/google
          naver:
            client-id: wN4NSFudlMRcqEReNS6r
            client-secret: i9SsnEUWBp
            scope:
              - email
              - profile
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: https://gymate.duckdns.org/login/oauth2/code/naver
          kakao:
            client-id: df46b4adae193eeb1400d6e2f753157b
            client-secret: NCnUe3hT9Q2yTvlBLNd9Gui77HdMN4w6
            redirect-uri: https://gymate.duckdns.org/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id