spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 405172535942-sc1t0tli99i1hh1po16ctoj8lcvpfmhn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: wN4NSFudlMRcqEReNS6r
            client-secret: i9SsnEUWBp
            scope:
              - email
              - profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response